// GENERATED by scripts/build-tokens.mjs from ./tokens.json. Do not edit by hand.
// Run `npm run build:tokens` after editing tokens.json.

export const tokenPrefix = "eui" as const;
export const themeAttribute = "data-theme" as const;
export const themes = ["light","dark"] as const;
export type ThemeName = (typeof themes)[number];

/** Raw primitive values (hex colors, rem sizes, clamp() expressions). */
export const primitive = {
  "color": {
    "white": "#ffffff",
    "black": "#000000",
    "neutral": {
      "50": "#f8f9fa",
      "100": "#f1f3f5",
      "200": "#e4e7eb",
      "300": "#c9cfd6",
      "400": "#858f9c",
      "500": "#5f6a78",
      "600": "#4a5462",
      "700": "#353d49",
      "800": "#242a33",
      "900": "#161b22",
      "950": "#0f1218"
    },
    "ink": {
      "canvas": "#0f1218",
      "surface": "#161b22",
      "subtle": "#1b2129",
      "raised": "#1f262f",
      "border": "#2b333d",
      "borderStrong": "#64707f",
      "text": "#e8ebef",
      "textSecondary": "#aab3bf",
      "textTertiary": "#8b95a3",
      "textDisabled": "#5f6a78"
    },
    "blue": {
      "50": "#eef3fb",
      "100": "#dbe5f7",
      "200": "#b8cbef",
      "300": "#8eade4",
      "400": "#6089d7",
      "500": "#3b67c9",
      "600": "#2a52b4",
      "700": "#234394",
      "800": "#1e3876",
      "900": "#1a2e5e"
    },
    "green": {
      "50": "#e7f5ec",
      "200": "#a9dcbc",
      "400": "#5fc78f",
      "600": "#1e6b45",
      "800": "#1f5a3c",
      "900": "#12291d"
    },
    "amber": {
      "50": "#fdf3df",
      "200": "#f0cf87",
      "400": "#e3b04f",
      "600": "#8a5a00",
      "800": "#6b4f12",
      "900": "#2e2410"
    },
    "red": {
      "50": "#fdeceb",
      "200": "#f2b3ae",
      "400": "#f28b84",
      "600": "#b3261e",
      "800": "#7a2c27",
      "900": "#341a19"
    }
  },
  "font": {
    "family": {
      "sans": "\"Inter Variable\", system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
      "mono": "\"JetBrains Mono Variable\", ui-monospace, SFMono-Regular, Menlo, Consolas, \"Liberation Mono\", monospace"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "size": {
      "display": "clamp(2.25rem, 1.75rem + 2vw, 3.5rem)",
      "heading1": "clamp(1.875rem, 1.55rem + 1.3vw, 2.5rem)",
      "heading2": "clamp(1.5rem, 1.35rem + 0.6vw, 1.875rem)",
      "heading3": "clamp(1.25rem, 1.2rem + 0.25vw, 1.375rem)",
      "heading4": "1.0625rem",
      "lead": "clamp(1.125rem, 1.08rem + 0.25vw, 1.25rem)",
      "body": "1rem",
      "compact": "0.875rem",
      "meta": "0.8125rem",
      "eyebrow": "0.8125rem"
    },
    "lineHeight": {
      "display": "1.08",
      "heading": "1.18",
      "subheading": "1.3",
      "lead": "1.55",
      "body": "1.6",
      "compact": "1.45",
      "tight": "1.25"
    },
    "tracking": {
      "display": "-0.022em",
      "heading": "-0.014em",
      "subheading": "-0.006em",
      "normal": "0",
      "eyebrow": "0.06em"
    }
  },
  "space": {
    "0": "0",
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "8": "2rem",
    "10": "2.5rem",
    "12": "3rem",
    "16": "4rem",
    "20": "5rem",
    "24": "6rem"
  },
  "container": {
    "reading": "42rem",
    "content": "72rem",
    "wide": "90rem",
    "gutter": "clamp(1rem, 4vw, 2.5rem)"
  },
  "radius": {
    "none": "0",
    "sm": "0.25rem",
    "md": "0.375rem",
    "lg": "0.625rem",
    "full": "999px"
  },
  "border": {
    "width": "1px",
    "widthStrong": "2px"
  },
  "control": {
    "sm": "2rem",
    "md": "2.5rem",
    "lg": "3rem",
    "touch": "2.75rem",
    "iconSm": "1rem",
    "iconMd": "1.25rem",
    "iconLg": "1.5rem"
  },
  "motion": {
    "fast": "120ms",
    "base": "180ms",
    "slow": "280ms",
    "easeStandard": "cubic-bezier(0.2, 0, 0, 1)",
    "easeEmphasized": "cubic-bezier(0.3, 0, 0, 1)"
  },
  "z": {
    "base": "0",
    "raised": "1",
    "sticky": "100",
    "dropdown": "200",
    "overlay": "300",
    "modal": "400",
    "toast": "500"
  },
  "focus": {
    "width": "2px",
    "offset": "2px"
  }
} as const;

/** Semantic roles per theme, fully resolved to concrete values. */
export const semantic = {
  "light": {
    "color": {
      "background": {
        "canvas": "#f8f9fa",
        "surface": "#ffffff",
        "subtle": "#f1f3f5",
        "raised": "#ffffff",
        "inverse": "#161b22",
        "overlay": "rgba(15, 18, 24, 0.45)"
      },
      "text": {
        "primary": "#161b22",
        "secondary": "#4a5462",
        "tertiary": "#5f6a78",
        "disabled": "#858f9c",
        "inverse": "#f8f9fa",
        "link": "#234394",
        "onAction": "#ffffff",
        "onDanger": "#ffffff",
        "inverseSecondary": "#c9cfd6",
        "inverseTertiary": "#858f9c"
      },
      "border": {
        "default": "#e4e7eb",
        "strong": "#858f9c",
        "subtle": "#f1f3f5",
        "inverse": "#353d49"
      },
      "action": {
        "primary": "#2a52b4",
        "primaryHover": "#234394",
        "primaryActive": "#1e3876",
        "secondary": "#161b22",
        "secondaryHover": "#242a33",
        "secondaryActive": "#353d49",
        "subtle": "#f1f3f5",
        "subtleHover": "#e4e7eb",
        "selected": "#eef3fb",
        "selectedStrong": "#2a52b4",
        "disabled": "#e4e7eb"
      },
      "status": {
        "success": "#1e6b45",
        "successSurface": "#e7f5ec",
        "successBorder": "#a9dcbc",
        "warning": "#8a5a00",
        "warningSurface": "#fdf3df",
        "warningBorder": "#f0cf87",
        "danger": "#b3261e",
        "dangerSurface": "#fdeceb",
        "dangerBorder": "#f2b3ae",
        "info": "#234394",
        "infoSurface": "#eef3fb",
        "infoBorder": "#b8cbef",
        "neutral": "#4a5462",
        "neutralSurface": "#f1f3f5",
        "neutralBorder": "#c9cfd6"
      },
      "focus": {
        "ring": "#2a52b4"
      },
      "data": {
        "1": "#2a52b4",
        "2": "#5f6a78",
        "3": "#1e6b45",
        "4": "#8a5a00",
        "5": "#8eade4",
        "6": "#c9cfd6"
      }
    },
    "shadow": {
      "overlay": "0 8px 24px -8px rgba(15, 18, 24, 0.22), 0 2px 6px rgba(15, 18, 24, 0.08)"
    }
  },
  "dark": {
    "color": {
      "background": {
        "canvas": "#0f1218",
        "surface": "#161b22",
        "subtle": "#1b2129",
        "raised": "#1f262f",
        "inverse": "#f1f3f5",
        "overlay": "rgba(0, 0, 0, 0.6)"
      },
      "text": {
        "primary": "#e8ebef",
        "secondary": "#aab3bf",
        "tertiary": "#8b95a3",
        "disabled": "#5f6a78",
        "inverse": "#161b22",
        "link": "#8eade4",
        "onAction": "#ffffff",
        "onDanger": "#161b22",
        "inverseSecondary": "#4a5462",
        "inverseTertiary": "#5f6a78"
      },
      "border": {
        "default": "#2b333d",
        "strong": "#64707f",
        "subtle": "#1b2129",
        "inverse": "#c9cfd6"
      },
      "action": {
        "primary": "#3b67c9",
        "primaryHover": "#2a52b4",
        "primaryActive": "#234394",
        "secondary": "#f1f3f5",
        "secondaryHover": "#e4e7eb",
        "secondaryActive": "#c9cfd6",
        "subtle": "#1f262f",
        "subtleHover": "#2b333d",
        "selected": "#1a2e5e",
        "selectedStrong": "#6089d7",
        "disabled": "#2b333d"
      },
      "status": {
        "success": "#5fc78f",
        "successSurface": "#12291d",
        "successBorder": "#1f5a3c",
        "warning": "#e3b04f",
        "warningSurface": "#2e2410",
        "warningBorder": "#6b4f12",
        "danger": "#f28b84",
        "dangerSurface": "#341a19",
        "dangerBorder": "#7a2c27",
        "info": "#8eade4",
        "infoSurface": "#1a2e5e",
        "infoBorder": "#1e3876",
        "neutral": "#aab3bf",
        "neutralSurface": "#1f262f",
        "neutralBorder": "#64707f"
      },
      "focus": {
        "ring": "#8eade4"
      },
      "data": {
        "1": "#8eade4",
        "2": "#8b95a3",
        "3": "#5fc78f",
        "4": "#e3b04f",
        "5": "#2a52b4",
        "6": "#64707f"
      }
    },
    "shadow": {
      "overlay": "0 12px 32px -8px rgba(0, 0, 0, 0.6), 0 2px 8px rgba(0, 0, 0, 0.4)"
    }
  }
} as const;

/** Semantic token path -> CSS custom property name. */
export const semanticVars = {
  "color.background.canvas": "--eui-color-background-canvas",
  "color.background.surface": "--eui-color-background-surface",
  "color.background.subtle": "--eui-color-background-subtle",
  "color.background.raised": "--eui-color-background-raised",
  "color.background.inverse": "--eui-color-background-inverse",
  "color.background.overlay": "--eui-color-background-overlay",
  "color.text.primary": "--eui-color-text-primary",
  "color.text.secondary": "--eui-color-text-secondary",
  "color.text.tertiary": "--eui-color-text-tertiary",
  "color.text.disabled": "--eui-color-text-disabled",
  "color.text.inverse": "--eui-color-text-inverse",
  "color.text.link": "--eui-color-text-link",
  "color.text.onAction": "--eui-color-text-on-action",
  "color.text.onDanger": "--eui-color-text-on-danger",
  "color.text.inverseSecondary": "--eui-color-text-inverse-secondary",
  "color.text.inverseTertiary": "--eui-color-text-inverse-tertiary",
  "color.border.default": "--eui-color-border-default",
  "color.border.strong": "--eui-color-border-strong",
  "color.border.subtle": "--eui-color-border-subtle",
  "color.border.inverse": "--eui-color-border-inverse",
  "color.action.primary": "--eui-color-action-primary",
  "color.action.primaryHover": "--eui-color-action-primary-hover",
  "color.action.primaryActive": "--eui-color-action-primary-active",
  "color.action.secondary": "--eui-color-action-secondary",
  "color.action.secondaryHover": "--eui-color-action-secondary-hover",
  "color.action.secondaryActive": "--eui-color-action-secondary-active",
  "color.action.subtle": "--eui-color-action-subtle",
  "color.action.subtleHover": "--eui-color-action-subtle-hover",
  "color.action.selected": "--eui-color-action-selected",
  "color.action.selectedStrong": "--eui-color-action-selected-strong",
  "color.action.disabled": "--eui-color-action-disabled",
  "color.status.success": "--eui-color-status-success",
  "color.status.successSurface": "--eui-color-status-success-surface",
  "color.status.successBorder": "--eui-color-status-success-border",
  "color.status.warning": "--eui-color-status-warning",
  "color.status.warningSurface": "--eui-color-status-warning-surface",
  "color.status.warningBorder": "--eui-color-status-warning-border",
  "color.status.danger": "--eui-color-status-danger",
  "color.status.dangerSurface": "--eui-color-status-danger-surface",
  "color.status.dangerBorder": "--eui-color-status-danger-border",
  "color.status.info": "--eui-color-status-info",
  "color.status.infoSurface": "--eui-color-status-info-surface",
  "color.status.infoBorder": "--eui-color-status-info-border",
  "color.status.neutral": "--eui-color-status-neutral",
  "color.status.neutralSurface": "--eui-color-status-neutral-surface",
  "color.status.neutralBorder": "--eui-color-status-neutral-border",
  "color.focus.ring": "--eui-color-focus-ring",
  "color.data.1": "--eui-color-data-1",
  "color.data.2": "--eui-color-data-2",
  "color.data.3": "--eui-color-data-3",
  "color.data.4": "--eui-color-data-4",
  "color.data.5": "--eui-color-data-5",
  "color.data.6": "--eui-color-data-6",
  "shadow.overlay": "--eui-shadow-overlay"
} as const;
export type SemanticTokenPath = keyof typeof semanticVars;

/** Primitive token path -> CSS custom property name. */
export const primitiveVars = {
  "color.white": "--eui-color-white",
  "color.black": "--eui-color-black",
  "color.neutral.50": "--eui-color-neutral-50",
  "color.neutral.100": "--eui-color-neutral-100",
  "color.neutral.200": "--eui-color-neutral-200",
  "color.neutral.300": "--eui-color-neutral-300",
  "color.neutral.400": "--eui-color-neutral-400",
  "color.neutral.500": "--eui-color-neutral-500",
  "color.neutral.600": "--eui-color-neutral-600",
  "color.neutral.700": "--eui-color-neutral-700",
  "color.neutral.800": "--eui-color-neutral-800",
  "color.neutral.900": "--eui-color-neutral-900",
  "color.neutral.950": "--eui-color-neutral-950",
  "color.ink.canvas": "--eui-color-ink-canvas",
  "color.ink.surface": "--eui-color-ink-surface",
  "color.ink.subtle": "--eui-color-ink-subtle",
  "color.ink.raised": "--eui-color-ink-raised",
  "color.ink.border": "--eui-color-ink-border",
  "color.ink.borderStrong": "--eui-color-ink-border-strong",
  "color.ink.text": "--eui-color-ink-text",
  "color.ink.textSecondary": "--eui-color-ink-text-secondary",
  "color.ink.textTertiary": "--eui-color-ink-text-tertiary",
  "color.ink.textDisabled": "--eui-color-ink-text-disabled",
  "color.blue.50": "--eui-color-blue-50",
  "color.blue.100": "--eui-color-blue-100",
  "color.blue.200": "--eui-color-blue-200",
  "color.blue.300": "--eui-color-blue-300",
  "color.blue.400": "--eui-color-blue-400",
  "color.blue.500": "--eui-color-blue-500",
  "color.blue.600": "--eui-color-blue-600",
  "color.blue.700": "--eui-color-blue-700",
  "color.blue.800": "--eui-color-blue-800",
  "color.blue.900": "--eui-color-blue-900",
  "color.green.50": "--eui-color-green-50",
  "color.green.200": "--eui-color-green-200",
  "color.green.400": "--eui-color-green-400",
  "color.green.600": "--eui-color-green-600",
  "color.green.800": "--eui-color-green-800",
  "color.green.900": "--eui-color-green-900",
  "color.amber.50": "--eui-color-amber-50",
  "color.amber.200": "--eui-color-amber-200",
  "color.amber.400": "--eui-color-amber-400",
  "color.amber.600": "--eui-color-amber-600",
  "color.amber.800": "--eui-color-amber-800",
  "color.amber.900": "--eui-color-amber-900",
  "color.red.50": "--eui-color-red-50",
  "color.red.200": "--eui-color-red-200",
  "color.red.400": "--eui-color-red-400",
  "color.red.600": "--eui-color-red-600",
  "color.red.800": "--eui-color-red-800",
  "color.red.900": "--eui-color-red-900",
  "font.family.sans": "--eui-font-family-sans",
  "font.family.mono": "--eui-font-family-mono",
  "font.weight.regular": "--eui-font-weight-regular",
  "font.weight.medium": "--eui-font-weight-medium",
  "font.weight.semibold": "--eui-font-weight-semibold",
  "font.weight.bold": "--eui-font-weight-bold",
  "font.size.display": "--eui-font-size-display",
  "font.size.heading1": "--eui-font-size-heading1",
  "font.size.heading2": "--eui-font-size-heading2",
  "font.size.heading3": "--eui-font-size-heading3",
  "font.size.heading4": "--eui-font-size-heading4",
  "font.size.lead": "--eui-font-size-lead",
  "font.size.body": "--eui-font-size-body",
  "font.size.compact": "--eui-font-size-compact",
  "font.size.meta": "--eui-font-size-meta",
  "font.size.eyebrow": "--eui-font-size-eyebrow",
  "font.lineHeight.display": "--eui-font-line-height-display",
  "font.lineHeight.heading": "--eui-font-line-height-heading",
  "font.lineHeight.subheading": "--eui-font-line-height-subheading",
  "font.lineHeight.lead": "--eui-font-line-height-lead",
  "font.lineHeight.body": "--eui-font-line-height-body",
  "font.lineHeight.compact": "--eui-font-line-height-compact",
  "font.lineHeight.tight": "--eui-font-line-height-tight",
  "font.tracking.display": "--eui-font-tracking-display",
  "font.tracking.heading": "--eui-font-tracking-heading",
  "font.tracking.subheading": "--eui-font-tracking-subheading",
  "font.tracking.normal": "--eui-font-tracking-normal",
  "font.tracking.eyebrow": "--eui-font-tracking-eyebrow",
  "space.0": "--eui-space-0",
  "space.1": "--eui-space-1",
  "space.2": "--eui-space-2",
  "space.3": "--eui-space-3",
  "space.4": "--eui-space-4",
  "space.5": "--eui-space-5",
  "space.6": "--eui-space-6",
  "space.8": "--eui-space-8",
  "space.10": "--eui-space-10",
  "space.12": "--eui-space-12",
  "space.16": "--eui-space-16",
  "space.20": "--eui-space-20",
  "space.24": "--eui-space-24",
  "container.reading": "--eui-container-reading",
  "container.content": "--eui-container-content",
  "container.wide": "--eui-container-wide",
  "container.gutter": "--eui-container-gutter",
  "radius.none": "--eui-radius-none",
  "radius.sm": "--eui-radius-sm",
  "radius.md": "--eui-radius-md",
  "radius.lg": "--eui-radius-lg",
  "radius.full": "--eui-radius-full",
  "border.width": "--eui-border-width",
  "border.widthStrong": "--eui-border-width-strong",
  "control.sm": "--eui-control-sm",
  "control.md": "--eui-control-md",
  "control.lg": "--eui-control-lg",
  "control.touch": "--eui-control-touch",
  "control.iconSm": "--eui-control-icon-sm",
  "control.iconMd": "--eui-control-icon-md",
  "control.iconLg": "--eui-control-icon-lg",
  "motion.fast": "--eui-motion-fast",
  "motion.base": "--eui-motion-base",
  "motion.slow": "--eui-motion-slow",
  "motion.easeStandard": "--eui-motion-ease-standard",
  "motion.easeEmphasized": "--eui-motion-ease-emphasized",
  "z.base": "--eui-z-base",
  "z.raised": "--eui-z-raised",
  "z.sticky": "--eui-z-sticky",
  "z.dropdown": "--eui-z-dropdown",
  "z.overlay": "--eui-z-overlay",
  "z.modal": "--eui-z-modal",
  "z.toast": "--eui-z-toast",
  "focus.width": "--eui-focus-width",
  "focus.offset": "--eui-focus-offset"
} as const;
export type PrimitiveTokenPath = keyof typeof primitiveVars;

