#!/usr/bin/env node
// Full package build: tokens -> TypeScript (dist/*.js + *.d.ts) -> dist/styles.css + dist/fonts.
import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const DIST = join(ROOT, "dist");
const run = (cmd, args) => execFileSync(cmd, args, { cwd: ROOT, stdio: "inherit" });

if (existsSync(DIST)) rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

// 1. tokens.json -> dist/tokens.css + src/tokens/generated.ts
run(process.execPath, [join(HERE, "build-tokens.mjs")]);

// 2. TypeScript -> dist (ESM + declarations)
run(join(ROOT, "node_modules", ".bin", "tsc"), ["-p", "tsconfig.build.json"]);

// 3. Stylesheet: fonts + tokens + base + component layers, in this order.
const layers = ["fonts.css", "../../dist/tokens.css", "base.css", "foundations.css", "controls.css", "display.css", "content.css"];
const css = layers
  .map((f) => {
    const p = f.startsWith("../") ? join(ROOT, "src", "styles", f) : join(ROOT, "src", "styles", f);
    return `/* ---- ${f.replace("../../dist/", "")} ---- */\n` + readFileSync(p, "utf8").trim() + "\n";
  })
  .join("\n");
writeFileSync(join(DIST, "styles.css"), `/* executive-ui ${JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version} - generated by scripts/build.mjs */\n` + css);

// 4. Fonts next to the stylesheet (paths in fonts.css are ./fonts/...).
cpSync(join(ROOT, "fonts"), join(DIST, "fonts"), { recursive: true });

console.log("build: dist/index.js, dist/index.d.ts, dist/styles.css, dist/tokens.css, dist/fonts/");
