#!/usr/bin/env node
// Generates dist/tokens.css and src/tokens/generated.ts from src/tokens/tokens.json.
// tokens.json is the only hand-edited token file.
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadTokens, flatten, varName, resolveRef } from "./token-lib.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const CHECK = process.argv.includes("--check");

const tokens = loadTokens();
const prefix = tokens.meta.prefix;
const attr = tokens.meta.themeAttribute;
const themes = tokens.meta.themes;
const defaultTheme = themes[0];

// ---- CSS ---------------------------------------------------------------
const lines = [];
lines.push(`/* GENERATED by scripts/build-tokens.mjs from src/tokens/tokens.json. Do not edit. */`);
lines.push(`/* Primitives: raw values. Semantic roles below reference them per theme. */`);
lines.push(`:root {`);
for (const [segs, value] of flatten(tokens.primitive)) {
  lines.push(`  ${varName(prefix, segs)}: ${value};`);
}
lines.push(`}`);
lines.push(``);
for (const theme of themes) {
  const selector =
    theme === defaultTheme ? `:root,\n[${attr}="${theme}"]` : `[${attr}="${theme}"]`;
  lines.push(`/* Theme: ${theme} */`);
  lines.push(`${selector} {`);
  lines.push(`  color-scheme: ${theme};`);
  for (const [segs, raw] of flatten(tokens.semantic[theme])) {
    const { value, ref } = resolveRef(raw, tokens.primitive);
    const rhs = ref ? `var(${varName(prefix, ref)})` : value;
    lines.push(`  ${varName(prefix, segs)}: ${rhs};`);
  }
  lines.push(`}`);
  lines.push(``);
}
const css = lines.join("\n");

// ---- TypeScript ------------------------------------------------------------
const ts = [];
ts.push(`// GENERATED by scripts/build-tokens.mjs from ./tokens.json. Do not edit by hand.`);
ts.push(`// Run \`npm run build:tokens\` after editing tokens.json.`);
ts.push(``);
ts.push(`export const tokenPrefix = ${JSON.stringify(prefix)} as const;`);
ts.push(`export const themeAttribute = ${JSON.stringify(attr)} as const;`);
ts.push(`export const themes = ${JSON.stringify(themes)} as const;`);
ts.push(`export type ThemeName = (typeof themes)[number];`);
ts.push(``);
ts.push(`/** Raw primitive values (hex colors, rem sizes, clamp() expressions). */`);
ts.push(`export const primitive = ${JSON.stringify(tokens.primitive, null, 2)} as const;`);
ts.push(``);
const resolved = {};
for (const theme of themes) {
  resolved[theme] = {};
  for (const [segs, raw] of flatten(tokens.semantic[theme])) {
    let cur = resolved[theme];
    for (const s of segs.slice(0, -1)) cur = cur[s] ??= {};
    cur[segs[segs.length - 1]] = resolveRef(raw, tokens.primitive).value;
  }
}
ts.push(`/** Semantic roles per theme, fully resolved to concrete values. */`);
ts.push(`export const semantic = ${JSON.stringify(resolved, null, 2)} as const;`);
ts.push(``);
// Flat list of every semantic CSS variable name (same for every theme).
const semanticVars = flatten(tokens.semantic[defaultTheme]).map(([segs]) => [segs.join("."), varName(prefix, segs)]);
ts.push(`/** Semantic token path -> CSS custom property name. */`);
ts.push(`export const semanticVars = ${JSON.stringify(Object.fromEntries(semanticVars), null, 2)} as const;`);
ts.push(`export type SemanticTokenPath = keyof typeof semanticVars;`);
const primitiveVars = flatten(tokens.primitive).map(([segs]) => [segs.join("."), varName(prefix, segs)]);
ts.push(``);
ts.push(`/** Primitive token path -> CSS custom property name. */`);
ts.push(`export const primitiveVars = ${JSON.stringify(Object.fromEntries(primitiveVars), null, 2)} as const;`);
ts.push(`export type PrimitiveTokenPath = keyof typeof primitiveVars;`);
ts.push(``);
const tsOut = ts.join("\n") + "\n";

const cssPath = join(ROOT, "dist", "tokens.css");
const tsPath = join(ROOT, "src", "tokens", "generated.ts");

if (CHECK) {
  const current = existsSync(tsPath) ? readFileSync(tsPath, "utf8") : "";
  if (current !== tsOut) {
    console.error("src/tokens/generated.ts is stale. Run `npm run build:tokens`.");
    process.exit(1);
  }
  console.log("tokens: generated.ts is up to date");
  process.exit(0);
}

mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(cssPath, css + "\n");
writeFileSync(tsPath, tsOut);
console.log(`tokens: wrote dist/tokens.css (${flatten(tokens.primitive).length} primitives, ${semanticVars.length} semantic roles x ${themes.length} themes) and src/tokens/generated.ts`);
